name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.1
  injectable: 1.0.0
  get_it: ^4.0.2
  rflutter_alert: ^1.0.3
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.1
  injectable_generator: 1.0.0

flutter:
  uses-material-design: true