name: learning_flutter
description: Learning how to make applications in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^1.3.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: 0.14.0+2
  modal_progress_hud: ^0.1.3
  json_serializable: ^3.5.0
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  freezed:

flutter:
  uses-material-design: true

  assets:
  - assets/images/
