name: learning_flutter
description: Learning how to make applications in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_spinkit: ^5.0.0
  http: ^0.13.3
  geolocator: ^7.0.3
  sprintf: ^6.0.0
  build_runner: ^2.0.3
  get_it: ^7.1.3
  flutter_bloc: ^7.0.1
  equatable: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: assets/fonts/SpartanMB-Black.otf
      weight: 900