name: learning_flutter
description: Learning how to make applications in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_spinkit: "^4.1.2"
  http: ^0.12.2
  geolocator: ^5.3.2+2
  sprintf: "^4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: assets/fonts/SpartanMB-Black.otf
      weight: 900